#!/usr/bin/env -S uv run --script
# /// script
#
# requires-python = ">=3.10"
#
# dependencies = [
#   "trame>=3.13",
#   "trame-vuetify",
#   "trame-vtk",
#   "trame-reveal",
#   "parsli",
#   "vtk<9.7",
# ]
#
# [[tool.uv.index]]
# url = "https://wheels.vtk.org"
#
# ///

import asyncio
from pathlib import Path

from trame.app import TrameApp
from trame.ui.vuetify3 import SinglePageLayout
from trame.widgets import vuetify3 as v3, vtk as vtkw

from trame.tools.reveal import SlideViewer

from parsli.viewer.core import Viewer

class Cone(TrameApp):
    def __init__(self, server_or_name=None):
        super().__init__(server_or_name)
        with SinglePageLayout(self.server) as self.ui:
            self.ui.title.set_text("Trame demo")
            with self.ui.toolbar as toolbar:
                toolbar.density = "compact"
                v3.VSpacer()
                v3.VSlider(
                    v_model=("resolution", 6),
                    min=3,
                    max=60,
                    step=1,
                    hide_details=True,
                    style="max-width: 300px;",
                )
                v3.VBtn(icon="mdi-lock-reset", click="resolution=6")
                v3.VBtn(icon="mdi-crop-free", click=self.ctrl.view_reset_camera)

            with self.ui.content:
                with v3.VContainer(fluid=True, classes="pa-0 fill-height"):
                    with vtkw.VtkView() as view:
                        self.ctrl.view_reset_camera = view.reset_camera
                        with vtkw.VtkGeometryRepresentation():
                            vtkw.VtkAlgorithm(
                                vtk_class="vtkConeSource",
                                state=("{ resolution }",),
                            )

def init_small(app):
    app.server.state.resolution = 3

async def init_large(app):
    while True:
        with app.server.state as s:
            s.resolution += 1
        await asyncio.sleep(0.1)
        if app.server.state.resolution > 60:
            app.server.state.resolution = 3

def init_parsli(app):
    with app.state as state:
        state.update({
        "coast_active_regions": ['asia' ],
        "color_by": "strike_slip",
        "color_max": 8.157,
        "color_min": -8.157,
        "color_preset": "Fast",
        "formula": "sign(strike_slip) * abs(strike_slip)^.5",
        "latitude_bnds": [30.386, 43.674],
        "light_rivers": False,
        "light_segment": False,
        "light_surface": False,
        "light_terrain": False,
        "longitude_bnds":[130.823, 146.75],
        "nb_contours": 16,
        "nb_grid_line_per_degree": -3,
        "rivers_opacity": 100,
        "segment_opacity": 1,
        "show_earth_core": False,
        "show_grid": True,
        "show_rivers": True,
        "show_segment": True,
        "show_surface": True,
        "show_terrain": True,
        "spherical": True,
        "subdivide": False,
        "surface_opacity": 100,
        "terrain_opacity": 100,
        "topo_ui": False,
        "use_formula": True,
        "vertical_scaling": 1,
        "vertical_scaling_topo": 1,
        "show_panel": False,
        })



def main():
    app = SlideViewer(
        content=Path(__file__).with_name("slides.html"),
        theme="kitware",
    )
    app.register_app(
        name="parsli",
        app=Viewer,
        initialize=init_parsli,
    )
    app.register_app(
        name="small-cone",
        app=Cone,
        initialize=init_small,

    )
    app.register_app(
        name="large-cone",
        app=Cone,
        initialize=init_large,
    )
    app.server.start()

if __name__ == "__main__":
    main()
