name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    needs: [pre-commit, pytest, test-npm-build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment:
      name: pypi
      url: https://pypi.org/p/trame-revealjs
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
      contents: write # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Fetch RevealJS files
        run: |
          cd src/trame_revealjs/serve/revealjs

          cur lhttps://unpkg.com/reveal.js@6.0.1/dist/reveal.js -Lo ./js/reveal.js
          curl https://unpkg.com/reveal.js@6.0.1/dist/plugin/notes.js -Lo ./js/notes.js
          curl https://unpkg.com/reveal.js@6.0.1/dist/plugin/markdown.js -Lo ./js/markdown.js
          curl https://unpkg.com/reveal.js@6.0.1/dist/plugin/highlight.js -Lo ./js/highlight.js

          curl https://unpkg.com/reveal.js@6.0.1/dist/reset.css -Lo ./css/reset.css
          curl https://unpkg.com/reveal.js@6.0.1/dist/reveal.css -Lo ./css/reveal.css
          curl https://unpkg.com/reveal.js@6.0.1/dist/theme/black.css -Lo ./css/black.css
          curl https://unpkg.com/reveal.js@6.0.1/dist/plugin/highlight/monokai.css -Lo ./css/monokai.css

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to PyPI
        if: steps.release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
